### PR TITLE
added DR12 BAO_FS and Lya-bao

### PR DESCRIPTION
**Pull request by ja-vazquez**
Likelihood used in the DR12 paper arXiv:1607.03155

### CODE REVIEW

**Comment by cmbant** [comment]
Many thanks for the patch!

I see your bao_FS.f90 seems to be duplicating a lot of the default bao.f90 module. Would it be possible to make the changes to bao.f90 instead of duplicating thing (or at least inherit from it)?

**Comment by ja-vazquez** [comment]
Hi Antony,

Yes, I’ll make the proper modifications and try to merge both files together.

Cheers,
Jose AV



On Aug 23, 2016, at 5:51 PM, Antony Lewis <notifications@github.com<mailto:notifications@github.com>> wrote:


Many thanks for the patch!

I see your bao_FS.f90 seems to be duplicating a lot of the default bao.f90 module. Would it be possible to make the changes to bao.f90 instead of duplicating thing (or at least inherit from it)?

**Comment by cmbant** [comment]
Did you get anywhere with merging the patch? Note that the default bao.f90 changed slightly this week as a I added support for a slightly more general file format.

**Comment by ja-vazquez** [comment]
Hi Anthony,

I haven’t yet, but I’ll do it perhaps over the course of this week.
I believe we are about to submit a similar paper but now for the BAO Lyman-a,
and I did more minor changes.
I’ll have a look of the new defaults bao.f90.

Thank you for letting me know
Jose A Vazquez

On Oct 28, 2016, at 12:13 PM, Antony Lewis <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you get anywhere with merging the patch? Note that the default bao.f90 changed slightly this week as a I added support for a slightly more general file format.

**Comment by cmbant** [comment]
In fd0d9fe3018ee9ad4b9347e6558076c291594f1d I added an update with the SDSS consensus data (but not Lyaman alpha. Similar to your changes, but I generalized the standard bao.f90 module rather than making a separate one.

**Pull request closed without merging**
