### PR TITLE
SDSSIII BOSS DR12 BAO and RSD

### PR DESCRIPTION
**Pull request by tomcharnock**
Added new batch and data files for SDSSIII BOSS DR12 BAO and RSD including:
- LOWZ and CMASS BAO from DR12 alpha_perp and alpha_plel consensus likelihoods
- LOWZ and CMASS RSD from DR12 with inverse covariance matrices from QPM and MD-PATCHY
Correction to DR11 LOWZ BAO rs_rescale to use values from 1312.4877 (~0.1% bias correction)

### CODE REVIEW

**Comment by cmbant** [comment]
Many thanks for this. A few small comments/queries:

Why is 6DF etc included in the BAODR12.ini file? (currently BAO.ini includes everything for DR11, not the DR11 file)?

Might be more consistent with other variables to rename Hz_rs_103 to bao_Hz_rs_103.

Rather than duplicating all the likelihood code for DR11 and DR12 (and CMASS/LOWZ), could it not be refactored into a common routines (e.g. looks like only Hrd_fid, DA_rd_fid are changing between the loglike files, so those could just be made parameters for a common routine?)

**Comment by cmbant** [comment]
Thanks for the update, looks neat. Sorry for delay in looking - it seems github doesn't send notifications when new commits are made but no comments added.

in sdss_DR11LOWZ_bao.dataset you seem to have "rs_rescale = 153.19/149.28", I think this needs to be a number? (please check all the BAO sets still run and return consistent results to the original)

"batch2" is meant to refer to Planck release 2, so it might be better not to modify the default BAO.ini there so people can still replicate Planck 2015 results if they want to. Perhaps put new defaults in batch2/BAO_new.ini? (or BAO.ini in a new batch3 folder)

**Comment by tomcharnock** [comment]
Hi Antony,
I wasn't having any problems using rs_rescale = 153.19/149.28 but I agree for consistency with the previous files I've changed this to a decimal format. All the BOSS DR12 batch files are now in batch3 (including a copy of BAO.ini with DEFAULT(BAODR11.ini) changed to DEFAULT(BAODR12.ini).
Hope this is all fine.
All the best,
Tom

**Comment by cmbant** [comment]
Many thanks for your contribution!

**Pull request merged**
