### PR TITLE
SPT-SZ 2500d TT code and data

### PR DESCRIPTION
**Pull request by clreichardt**
This request has two independent bits:
1) Changes to CMBlikes.f90:
         * option: aberration correction.
         * option: calibration term prior

2) Adding the set of files for the SPT-SZ 2500d TT power spectrum (see Story et al)

### CODE REVIEW

**Comment by cmbant** [comment]
Some queries/comments/suggestions:

AddAberration looks as though it's also potentially acting on the lensing potential; should probably be restricted to only CMB-type maps? (since the effect of aberration for lensing reconstruction is just to add an L=1 mode, at least to lowest order) You could do this like for the calibration in AdaptTheoryForMaps.

I would be inclined to give calibration_prior a more explicit name, e.g. "log_calibration_prior". (usually a Gaussian prior on the calibration is set via "prior[cal_param_name] = mean std" in the run .ini file).

It looks as though "cal_uncertainty" in your .dat file is not actually read in, and calibration_prior is not set? Did you forget to add "calibration_param = namefile.names"? (see planck_lensing folder example .dataset). For sampling "param[cal_param_name] = centre min max width width" in the SPTsz_2500deg2_TT.ini?

cl_deriv looks like it could be allocated locally in AddAberration. 

Probably want the .ini file in batch2 or batch3 not batch1 (the latter was for Planck 2013 settings, the latter for 2015; batch3 coming up).

Renaming "spt_s13_margfg.dat" to "spt_s13_margfg.dataset" would be more consistent with all implementations.

You can if you want skip things like "cl_hat_order" in the .dataset file and put a "# L TT" header in the .dat file instead.

Why is there a "spt_s13_margfg_cl_fiducial.dat" file full of zeros? (since you are using gaussian not HL likelihood, probably don't need it?). likewise spt_s13_margfg_cl_noise.dat?

aberration_coeff is defined as real(mcp) which is usually double, but being read as real. You can use "Ini%Read('name', this%param)" to get the right type automatically (initialising this%param to the default value in the type declaration).

(One could argue whether aberration is before or after adding foreground, e.g. for galactic vs CIB/SZ. I guess in practice is it is academic as the spectra are very smooth so aberration has almost no effect on the foreground model anyway. )

**Comment by clreichardt** [comment]
AddAberration looks as though it's also potentially acting on the lensing potential; should probably be restricted to only CMB-type maps? (since the effect of aberration for lensing reconstruction is just to add an L=1 mode, at least to lowest order) You could do this like for the calibration in AdaptTheoryForMaps.
—> Added a check for Cls(i,j)%CL being allocated.

I would be inclined to give calibration_prior a more explicit name, e.g. "log_calibration_prior". (usually a Gaussian prior on the calibration is set via "prior[cal_param_name] = mean std" in the run .ini file).
—> name changed. Also shifted to Ini%Read as suggested for aberration_coeff below.

It looks as though "cal_uncertainty" in your .dat file is not actually read in, and calibration_prior is not set? Did you forget to add "calibration_param = namefile.names"? (see planck_lensing folder example .dataset). For sampling "param[cal_param_name] = centre min max width width" in the SPTsz_2500deg2_TT.ini?
—> I’d forgotten in pushing the code that it was implemented differently in the dataset file in a period when we were trying to avoid needing to change the code. With that said, since we are pushing code changes, I’ve brought the dataset back to the more proper treatment.


cl_deriv looks like it could be allocated locally in AddAberration.
-> moved to a local var in AddAberration

Probably want the .ini file in batch2 or batch3 not batch1 (the latter was for Planck 2013 settings, the latter for 2015; batch3 coming up).
—> moved to batch3


Renaming "spt_s13_margfg.dat" to "spt_s13_margfg.dataset" would be more consistent with all implementations.
—> done

You can if you want skip things like "cl_hat_order" in the .dataset file and put a "# L TT" header in the .dat file instead.
—> left as is

Why is there a "spt_s13_margfg_cl_fiducial.dat" file full of zeros? (since you are using gaussian not HL likelihood, probably don't need it?). likewise spt_s13_margfg_cl_noise.dat?
—> I’ve deleted them.

aberration_coeff is defined as real(mcp) which is usually double, but being read as real. You can use "Ini%Read('name', this%param)" to get the right type automatically (initialising this%param to the default value in the type declaration).

—> swapped

(One could argue whether aberration is before or after adding foreground, e.g. for galactic vs CIB/SZ. I guess in practice is it is academic as the spectra are very smooth so aberration has almost no effect on the foreground model anyway. )

—> Fair, although I’ve left it as is.

**Comment by cmbant** [comment]
Thanks for the update.

I don't think  check for Cls(i,j)%CL is sufficient in general, you also need the test on the field type as at
https://github.com/cmbant/CosmoMC/blob/master/source/CMBlikes.f90#L1048

Otherwise looks good by eye.

**Comment by cmbant** [comment]
Two further comment: I think ncl_hat in the dataset file is not used, and you could if you wanted make it easier for people to plot the data by adding an "L_av" column (and maybe L_min, L_max) to the bandpower .dat file (as in planck_lensing, though people can of course work it out from the window functions).

I attempted to update python/CMBlikes.py to match if you want to check it.

**Pull request merged**
